from turtle import *
penup()
goto(-400,0)
pendown()
factor = 2
color('black')
pensize(15 * factor)
speed(100)
printing = 0
def pixel():
    penup()
    pendown()
    forward(0)
    penup()
    
def Test():
    left(90)
    for i in range(5):
        pixel()
        forward(10 * factor)
    right(90)
    forward(10 * factor)
    left(90)
def printA():
    left(90)
    for i in range(5):
        pixel()
        forward(10 * factor)
    penup()
    right(90)
    forward(10 * factor)
    pendown()
    pixel()
    penup()
    forward(10 * factor)
    left(90)
    forward(10 * factor)
    right(90)
    pendown()
    for i in range(3):
        pixel()
        forward(10 * factor)
    penup()
    right(180)
    forward(10 * factor)
    left(90)
    pendown()
    for i in range(7):
        pixel()
        forward(10 * factor)
    penup()
    right(180)
    forward(10 * factor)
    forward(10 * factor)
    left(90)
    for i in range(3):
        forward(10 * factor)
    left(180)
    for i in range(3):
        pixel()
        forward(10 * factor)
    right(90)
    forward(10 * factor)
    left(90)
    forward(10 * factor)
    forward(10 * factor)

def printb():
    for i in range(7):
        pixel()
        left(90)
        forward(10 * factor)
        right(90)
    forward(10 * factor)
    right(90)
    forward(10 * factor)
    left(90)
    for i in range(3):
        pixel()
        forward(10 * factor)
    right(90)
    forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
    right(90)
    forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
    right(180)
    for i in range(3):
        pixel()
        forward(10 * factor)
    right(90)
    forward(10 * factor)
    left(90)
    pixel()
    right(90)
    forward(10 * factor)
    left(90)
    pixel()
    right(90)
    forward(10 * factor)
    right(90)
    forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
    right(180)
    for i in range(3):
        pixel()
        forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
def printB():
    for i in range(7):
        pixel()
        left(90)
        forward(10 * factor)
        right(90)
    forward(10 * factor)
    right(90)
    forward(10 * factor)
    left(90)
    for i in range(3):
        pixel()
        forward(10 * factor)
    right(90)
    forward(10 * factor)
    pixel()
    forward(10 * factor)
    pixel()
    forward(10 * factor)
    right(90)
    forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
    right(180)
    for i in range(3):
        pixel()
        forward(10 * factor)
    right(90)
    forward(10 * factor)
    left(90)
    pixel()
    right(90)
    forward(10 * factor)
    left(90)
    pixel()
    right(90)
    forward(10 * factor)
    right(90)
    forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
    right(180)
    for i in range(3):
        pixel()
        forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
def printGe():
    for i in range(7):
        pixel()
        left(90)
        forward(10 * factor)
        right(90)
    forward(10 * factor)
    right(90)
    forward(10 * factor)
    left(90)
    for i in range(3):
        pixel()
        forward(10 * factor)
    right(90)
    forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
    forward(10 * factor)
    left(90)
    forward(10 * factor)
def printD():
    pixel()
    left(90)
    forward(10 * factor)
    pixel()
    right(90)
    forward(10 * factor)
    pixel()
    left(90)
    for i in range(4):
        forward(10 * factor)
        pixel()
    forward(10 * factor)
    right(90)
    forward(10 * factor)
    pixel()
    forward(10 * factor)
    pixel()
    right(90)
    for i in range(5):
        forward(10 * factor)
        pixel()
    right(90)
    forward(10 * factor)
    pixel()
    left(180)
    forward(10 * factor)
    forward(10 * factor)
    pixel()
    right(90)
    forward(10 * factor)
    pixel()
    left(90)
    forward(10 * factor)
    forward(10 * factor)
def printE():
    pixel()
    forward(10 * factor)
    for i in range(3):
        pixel()
        forward(10 * factor)
    left(180)
    for i in range(4):
        forward(10 * factor)
    right(90)
    for i in range(3):
        pixel()
        forward(10 * factor)
    right(90)
    for i in range(4):
        pixel()
        forward(10 * factor)
    left(180)
    for i in range(4):
        forward(10 * factor)
    right(90)
    for i in range(3):
        pixel()
        forward(10 * factor)
    right(90)
    for i in range(4):
        pixel()
        forward(10 * factor)
    left(180)
    for i in range(4):
        forward(10 * factor)
    left(90)
    forward(10 * factor)
    for i in range(5):
        forward(10 * factor)
    left(90)
    for i in range(6):
        forward(10 * factor)
def printio():
    pixel()
    forward(10 * factor)
    for i in range(3):
        pixel()
        forward(10 * factor)
    left(180)
    for i in range(4):
        forward(10 * factor)
    right(90)
    for i in range(2):
        pixel()
        forward(10 * factor)
    right(90)
    for i in range(4):
        pixel()
        forward(10 * factor)
    left(180)
    for i in range(4):
        forward(10 * factor)
    right(90)
    for i in range(2):
        pixel()
        forward(10 * factor)
    right(90)
    for i in range(4):
        pixel()
        forward(10 * factor)
    left(180)
    for i in range(2):
        forward(10 * factor)
    right(90)
    forward(10 * factor)
    forward(10 * factor)
    pixel()
    right(90)
    forward(10 * factor)
    forward(10 * factor)
    pixel()
    for i in range(3):
        forward(10 * factor)
    left(90)
    for i in range(6):
        forward(10 * factor)